"""empty message

Revision ID: 040b56393c94
Revises: 0f31b525ca68
Create Date: 2024-11-08 17:47:15.557009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040b56393c94'
down_revision = '0f31b525ca68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('auth_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('auth_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
