"""empty message

Revision ID: 0f31b525ca68
Revises: 1aac8aec2847
Create Date: 2024-11-08 14:59:17.608713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f31b525ca68'
down_revision = '1aac8aec2847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_key', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('auth_key')

    # ### end Alembic commands ###
