"""empty message

Revision ID: 1aac8aec2847
Revises: d09d6ed9c6b8
Create Date: 2024-11-08 10:22:31.969018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aac8aec2847'
down_revision = 'd09d6ed9c6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=80), nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('auth', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
